version:  "3.9"

services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 250M